data = [
    {
        "id": "1",
        "name": "JavaScript",
        "released_year": "1995",
        "githut_rank": "1",
        "link": "https://www.javascript.com",
        "thumbnail": "/images/languages-pics/Javascript.jpg",
        "description": "JavaScript, often abbreviated as JS, is a programming language that conforms to the ECMAScript specification. JavaScript is high-level, often just-in-time compiled, and multi-paradigm. It has curly-bracket syntax, dynamic typing, prototype-based object-orientation, and first-class functions.",
    },
    {
        "id": "2",
        "name": "Python",
        "released_year": "1991",
        "githut_rank": "2",
        "link": "https://www.python.org",
        "thumbnail": "/images/languages-pics/Python.jpg",
        "description": "Python is an interpreted high-level general-purpose programming language. Python's design philosophy emphasizes code readability with its notable use of significant indentation. Its language constructs as well as its object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.",
    },
    {
        "id": "3",
        "name": "Java",
        "released_year": "1995",
        "githut_rank": "3",
        "link": "https://www.java.com",
        "thumbnail": "/images/languages-pics/Java.jpg",
        "description": "Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible. It is a general-purpose programming language intended to let application developers write once, run anywhere, meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.",
    },
    {
        "id": "4",
        "name": "TypeScript",
        "released_year": "2012",
        "githut_rank": "7",
        "link": "https://www.typescriptlang.org/",
        "thumbnail": "/images/languages-pics/TypeScript.jpg",
        "description": "TypeScript is a programming language developed and maintained by Microsoft. It is a strict syntactical superset of JavaScript and adds optional static typing to the language. TypeScript is designed for the development of large applications and transcompiles to JavaScript",
    },
    {
        "id": "5",
        "name": "C#",
        "released_year": "2000",
        "githut_rank": "9",
        "link": "https://docs.microsoft.com/en-us/dotnet/csharp/",
        "thumbnail": "/images/languages-pics/CSharp.jpg",
        "description": "C# is a general-purpose, multi-paradigm programming language encompassing static typing, strong typing, lexically scoped, imperative, declarative, functional, generic, object-oriented, and component-oriented programming disciplines",
    },
    {
        "id": "6",
        "name": "PHP",
        "released_year": "1995",
        "githut_rank": "8",
        "link": "https://www.php.net",
        "thumbnail": "/images/languages-pics/PHP.jpg",
        "description": "PHP is a general-purpose scripting language geared towards web development. It was originally created by Danish-Canadian programmer Rasmus Lerdorf in 1994. The PHP reference implementation is now produced by The PHP Group. PHP originally stood for Personal Home Page, but it now stands for the recursive initialism PHP: Hypertext Preprocessor",
    },
    {
        "id": "7",
        "name": "C++",
        "released_year": "1985",
        "githut_rank": "5",
        "link": "http://www.cplusplus.org",
        "thumbnail": "/images/languages-pics/C++.jpg",
        "description": 'C++ is a general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language, or "C with Classes". The language has expanded significantly over time, and modern C++ now has object-oriented, generic, and functional features in addition to facilities for low-level memory manipulation.',
    },
    {
        "id": "8",
        "name": "C",
        "released_year": "1972",
        "githut_rank": "10",
        "link": "https://www.cprogramming.com",
        "thumbnail": "/images/languages-pics/C.jpg",
        "description": "C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, with a static type system. By design, C provides constructs that map efficiently to typical machine instructions.",
    },
    {
        "id": "9",
        "name": "Ruby",
        "released_year": "1995",
        "githut_rank": "6",
        "link": "https://www.ruby-lang.org/en/",
        "thumbnail": "/images/languages-pics/Ruby.jpg",
        "description": 'Ruby is an interpreted, high-level, general-purpose programming language. It was designed and developed in the mid-1990s by Yukihiro "Matz" Matsumoto in Japan. Ruby is dynamically typed and uses garbage collection and just-in-time compilation.',
    },
    {
        "id": "10",
        "name": "R",
        "released_year": "1993",
        "githut_rank": "33",
        "link": "https://www.r-project.org",
        "thumbnail": "/images/languages-pics/R.jpg",
        "description": "R is a programming language and free software environment for statistical computing and graphics supported by the R Core Team and the R Foundation for Statistical Computing. The R language is widely used among statisticians and data miners for developing statistical software and data analysis.",
    },
    {
        "id": "11",
        "name": "Objective-C",
        "released_year": "1984",
        "githut_rank": "18",
        "link": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html",
        "thumbnail": "/images/languages-pics/Objective-C.jpg",
        "description": "Objective-C is a general-purpose, object-oriented programming language that adds Smalltalk-style messaging to the C programming language. Originally developed by Brad Cox and Tom Love in the early 1980s, it was selected by NeXT for its NeXTSTEP operating system.",
    },
    {
        "id": "12",
        "name": "Swift",
        "released_year": "2015",
        "githut_rank": "16",
        "link": "https://swift.org/",
        "thumbnail": "/images/languages-pics/Swift.jpg",
        "description": "Swift is a general-purpose, multi-paradigm, compiled programming language developed by Apple Inc. and the open-source community. First released in 2014, Swift was developed as a replacement for Apple's earlier programming language Objective-C, as Objective-C had been largely unchanged since the early 1980s and lacked modern language features.",
    },
    {
        "id": "13",
        "name": "Kotlin",
        "released_year": "2011",
        "githut_rank": "15",
        "link": "https://kotlinlang.org",
        "thumbnail": "/images/languages-pics/Kotlin.jpg",
        "description": "Kotlin is a cross-platform, statically typed, general-purpose programming language with type inference. Kotlin is designed to interoperate fully with Java, and the JVM version of Kotlin's standard library depends on the Java Class Library, but type inference allows its syntax to be more concise.",
    },
    {
        "id": "14",
        "name": "Go",
        "released_year": "2009",
        "githut_rank": "4",
        "link": "https://golang.org",
        "thumbnail": "/images/languages-pics/Go.jpg",
        "description": "Go is a statically typed, compiled programming language designed at Google by Robert Griesemer, Rob Pike, and Ken Thompson. Go is syntactically similar to C, but with memory safety, garbage collection, structural typing, and CSP-style concurrency.",
    },
    {
        "id": "15",
        "name": "Rust",
        "released_year": "2010",
        "githut_rank": "14",
        "link": "https://www.rust-lang.org",
        "thumbnail": "/images/languages-pics/Rust.jpg",
        "description": "Rust is a multi-paradigm, high-level, general-purpose programming language designed for performance and safety, especially safe concurrency. Rust is syntactically similar to C++, but can guarantee memory safety by using a borrow checker to validate references.",
    },
    {
        "id": "16",
        "name": "Scala",
        "released_year": "2004",
        "githut_rank": "11",
        "link": "https://scala-lang.org",
        "thumbnail": "/images/languages-pics/Scala.jpg",
        "description": "Scala is a strong statically typed general-purpose programming language which supports both object-oriented programming and functional programming. Designed to be concise, many of Scala's design decisions are aimed to address criticisms of Java. Scala source code can be compiled to Java bytecode and run on a Java virtual machine.",
    },
]
